class ProfileSetupBrandCatalog {
  const ProfileSetupBrandCatalog._();

  static const int featuredLimit = 8;

  static const List<String> allBrands = [
    'Nike',
    'Adidas',
    'Puma',
    'Gucci',
    'Prada',
    'Zara',
    'H&M',
    'Uniqlo',
    'Louis Vuitton',
    'Balenciaga',
    'Chanel',
    'Dior',
    'Versace',
    'Burberry',
    'Armani',
    'Fendi',
    'Valentino',
    'Givenchy',
    'Saint Laurent',
    'Moncler',
    'Tommy Hilfiger',
    'Calvin Klein',
    'Ralph Lauren',
    'Levi\'s',
    'New Balance',
    'Reebok',
    'ASICS',
    'Converse',
    'Vans',
    'Under Armour',
    'Skechers',
    'The North Face',
    'Patagonia',
    'Lululemon',
    'Mango',
    'Massimo Dutti',
    'Bershka',
    'Pull&Bear',
    'Stradivarius',
    'Diesel',
    'Guess',
    'Superdry',
    'Lacoste',
    'Hugo Boss',
    'Coach',
    'Michael Kors',
    'Kate Spade',
    'Marc Jacobs',
    'Off-White',
    'Bape',
    'Supreme',
    'Jordan',
    'Crocs',
    'Aldo',
    'Steve Madden',
    'Miu Miu',
    'Dolce & Gabbana',
    'Salvatore Ferragamo',
    'Bottega Veneta',
    'Celine',
  ];
}
